Repository Spencer-T-Morris/Javascript_Group_Project, pull requests merged in 2019-12, with the labels that each got.

#1 added link to book readme
  booklist/bookinfo.md
  booklist/booklist.md
Labels: documentation, review

#3 pull request test
  teamnotes.md
Labels: good first issue

#7 added figma folder
  booklist/bookinfo.md
  booklist/images/AgileDev.jpg
  booklist/images/CleanCoder.jpg
  booklist/images/DesignPatterns.jpg
  booklist/images/Peopleware.jpg
  booklist/images/Pragcoder.jpg
  booklist/images/TDD.jpg
  booklist/images/cleancode.jpg
  booklist/images/coder.jpg
  booklist/images/devrelations.jpg
  booklist/images/eloJS.jpg
  booklist/images/legacycode.jpg
  booklist/images/phoenixprj.jpg
  booklist/images/softwareDevguide.jpg
  booklist/images/the pragmatic programmer.jpg
  booklist/images/unicornPro.jpg
  figma files/readITbooks.fig
  resources.md
  teamnotes.md
Labels: documentation, review

#13 Monaswork
  aboutUsImages/Mona.jpg
  aboutUsImages/Ryan.jpg
  aboutUsImages/Sam.jpg
  aboutUsImages/group.jpg
  aboutUsImages/spencer.jpg
  html files/aboutus.html
  html files/index.html
  html files/landing.html
Labels: enhancement, review

#15 Monaswork
  booklist/bookinfo.md
  booklist/images/htmlcss.jpg
  booklist/images/jsandjquery.jpg
  booklist/images/leanandagile.jpg
  html files/advanced.html
  html files/begin.html
  html files/career.html
  html files/fiction.html
  html files/intermediate.html
  html files/prodev.html
Labels: CSS styling needed, HTML done, enhancement, review

#16 Monaswork
  booklist/bookinfo.md
  html files/advanced.html
  html files/career.html
  html files/landing.html
Labels: CSS styling needed, HTML done, review

#17 Monaswork
  CSS/contactus.css
  booklist/bookinfo.md
  html files/advanced.html
  html files/begin.html
  html files/career.html
  html files/contactus.html
  html files/fiction.html
  html files/intermediate.html
  html files/prodev.html
  teamnotes.md
Labels: HTML done, review

#27 Monaswork contact form rough draft
  CSS/contactus.css
  aboutUsImages/Mona1.jpg
  aboutUsImages/Ryan1.jpg
  aboutUsImages/Sam1.jpg
  aboutUsImages/spencer1.jpg
  html files/contactus.html
Labels: enhancement, question, review

#30 Monaswork contact us page styling
  CSS/contactus.css
  aboutUsImages/GCAHBC logo.jpg
  aboutUsImages/GCGRlogo.png
  aboutUsImages/GCcirclelogo.png
  html files/contactus.html
  html files/landing.html
Labels: bug, documentation, help wanted
